# version: '3.8'
services:
  devcontainer:
    build: 
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ../..:/workspaces:cached
      - ~/.gitconfig:/home/nonroot/.gitconfig:cached
