# version: '3.8'
services:
  devcontainer:
    build: 
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ../..:/workspaces:cached
      - ~/.gitconfig:/home/node/.gitconfig:cached
      - /var/run/docker.sock:/var/run/docker.sock
